version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://kyc_user:kyc_password@db:5432/kyc_platform
      - NEXTAUTH_SECRET=your-secret-key-here-change-this
      - NEXTAUTH_URL=http://localhost:3000
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=kyc_user
      - POSTGRES_PASSWORD=kyc_password
      - POSTGRES_DB=kyc_platform
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: